# ICD9/ICD10 codes for conditions of interest
library(tidyverse)
library(icd)
library(icdplus)

get_cond_codes <- function(){
  
  out_list = list(
    
    abdominal_pain = list(label="Abdominal pain",
                          icd9_codes=c(children("7890"),
                                       get_icd_from_ccs(c(NA))) %>% as.character(),
                          icd10_codes=c(children(c("R10")),
                                        get_icd_from_ccs(c(NA),10)) %>% as.character(),
                          group="Gastrointestinal Symptoms",
                          include=TRUE,
                          hosp=TRUE),
    
    acute_bronchitis = list(label="Acute Bronchitis",
                            icd9_codes=c(children(c("466")),
                                         get_icd_from_ccs(c(NA))) %>% as.character(),
                            icd10_codes=c(children(c("J20","J21")),
                                          get_icd_from_ccs(c(NA),10)) %>% as.character(),
                            group="Respiratory Infection",
                            include=TRUE,
                            hosp=TRUE),
    
    chronic_bronchitis = list(label="Chronic Bronchitis",
                            icd9_codes=c(children(c("491")),
                                         get_icd_from_ccs(c(NA))) %>% as.character(),
                            icd10_codes=c(children(c("491")) %>% icd9_to_icd10(),
                                          get_icd_from_ccs(c(NA),10)) %>% as.character(),
                            group="Respiratory Infection",
                            include=TRUE,
                            hosp=TRUE),
    
    unspecified_upper_resp = list(label="Upper Respiratory Infection-Unspecified",
                                  icd9_codes=c(children(c("465")),
                                               get_icd_from_ccs(c(NA))) %>% as.character(),
                                  icd10_codes=c(children(c("465")) %>% icd9_to_icd10(),
                                                get_icd_from_ccs(c(NA),10)) %>% as.character(),
                                  group="Respiratory Infection",
                                  include=TRUE,
                                  hosp=TRUE),
    
    ascites = list(label="Ascites",
                   icd9_codes=c(children(c("7895")),
                                get_icd_from_ccs(c(NA))) %>% as.character(),
                   icd10_codes=c(children(c("R180","R188")),
                                 get_icd_from_ccs(c(NA),10)) %>% as.character(),
                   group="Hepatobiliary",
                   include=TRUE,
                   hosp=FALSE),
    
    aspergillosis = list(label="Aspergillosis associated disease",
                         icd9_codes=c(children(c("5186","4846","1173")),
                                      get_icd_from_ccs(c(NA))) %>% as.character(),
                         icd10_codes=c(children(c("B449","B440","B4481")),
                                       get_icd_from_ccs(c(NA),10)) %>% as.character(),
                         group="Respiratory Infection",
                         include=TRUE,
                         hosp=FALSE),
    
    asthma = list(label="Asthma",
                  icd9_codes=as.character(get_icd_from_ccs(c(128))),
                  icd10_codes=as.character(get_icd_from_ccs(c(128),icd_version = 10)),
                  group="Respiratory",
                  include=TRUE,
                  hosp=TRUE),
    
    bronchiectasis = list(label="Bronchiectasis",
                          icd9_codes=as.character(c(children("494"))),
                          icd10_codes=as.character(children("J47")),
                          group="Respiratory Infection",
                          include=TRUE,
                          hosp=TRUE),
    
    cancer_combined = list(label="Cancer of colon, stomach, GI organs",
                           icd9_codes=c(#children(c("99999")),
                             get_icd_from_ccs(c(13,14,18))) %>% as.character(),
                           icd10_codes=c(#children(c("99999")),
                             get_icd_from_ccs(c(13,14,18),10)) %>% as.character(),
                           group="Gastrointestinal",
                           include=TRUE,
                           hosp=FALSE),
    
    constipation = list(label="Constipation",
                        icd9_codes=as.character(children(c("5640"))),
                        icd10_codes=as.character(children(c("K590"))),
                        group="Gastrointestinal Symptoms",
                        include=TRUE,
                        hosp=TRUE),
    
    cholelithiasis =  list(label="Cholelithiasis",
                           icd9_codes=c(children(c("574")),
                                        get_icd_from_ccs(c(NA))) %>% as.character(),
                           icd10_codes=c(children(c("K80")),
                                         get_icd_from_ccs(c(NA),10)) %>% as.character(),
                           group="Hepatobiliary",
                           include=TRUE,
                           hosp=TRUE),
    
    cirrhosis = list(label="Cirrhosis",
                     icd9_codes=c(children(c("5715","5719","5716")),
                                  get_icd_from_ccs(c(NA))) %>% as.character(),
                     icd10_codes=c(children(c("K74")),
                                   get_icd_from_ccs(c(NA),10)) %>% as.character(),
                     group="Hepatobiliary",
                     include=TRUE,
                     hosp=FALSE),
    
    clubbing = list(label="Hypertrophic osteoarthropathy/clubbing",
                    icd9_codes=c(children(c("7815","7312")),
                                 get_icd_from_ccs(c(NA))) %>% as.character(),
                    icd10_codes=c(children(c("M8940","R683")),
                                  get_icd_from_ccs(c(NA),10)) %>% as.character(),
                    group="Bone",
                    include=TRUE,
                    hosp=FALSE),
    
    
    cystic_lung =  list(label="Congenital cystic lung",
                        icd9_codes = as.character(children(c("7484"))),
                        icd10_codes = as.character(c("Q330")),
                        group="Respiratory",
                        include=TRUE,
                        hosp=FALSE),
    
    dehydration = list(label="Dehydration",
                       icd9_codes = as.character(children(c("27651"))),
                       icd10_codes = as.character(c("E860")),
                       group="Renal",
                       include=TRUE,
                       hosp=TRUE),
    
    diabetes_type1_secondary = list(label="Diabetes (Type 1 or Secondary)",
                                    icd9_codes = c(as.character(c(children(c(paste0("250",0:9,rep(c(1,3),each=10))))),"V5867"),
                                                   c(as.character(children("249")),
                                                     get_icd_from_ccs(c(49,50))[!(get_icd_from_ccs(c(49,50)) %in% 
                                                                                    c(as.character(c(children(c(paste0("250",0:9,rep(c(1,3),each=10))))),"V5867"),
                                                                                      as.character(children(c(paste0("250",0:9,rep(c(0,2),each=10)))))))])),
                                    icd10_codes = c(c(get_icd_from_ccs(c(49,50),10)[str_detect(get_icd_from_ccs(c(49,50),10),"E10")],"Z794"),
                                                    c(get_icd_from_ccs(c(49,50),10)[!(get_icd_from_ccs(c(49,50),10) %in% 
                                                                                        c(c(get_icd_from_ccs(c(49,50),10)[str_detect(get_icd_from_ccs(c(49,50),10),"E10")],"Z794"),
                                                                                          get_icd_from_ccs(c(49,50),10)[str_detect(get_icd_from_ccs(c(49,50),10),"E11")]))])),
                                    group="Endocrine & Nutritional",
                                    include=TRUE,
                                    hosp=FALSE),
    
    diarrhea = list(label="Diarrhea",
                    icd9_codes=c(children(c("78791")),
                                 get_icd_from_ccs(c(NA))) %>% as.character(),
                    icd10_codes=c(children(c("R197")),
                                  get_icd_from_ccs(c(NA),10)) %>% as.character(),
                    group="Gastrointestinal Symptoms",
                    include=TRUE),
    
    esophagitis = list(label="Eosinophilic Esophagitis",
                       icd9_codes=c(children(c("53013")),
                                    get_icd_from_ccs(c(NA))) %>% as.character(),
                       icd10_codes=c(children(c("K200")),
                                     get_icd_from_ccs(c(NA),10)) %>% as.character(),
                       group="Gastrointestinal Symptoms",
                       include=TRUE),
    
    failure_to_thrive_adult = list(label="Cachexia and Adult Failure to thrive",
                                   icd9_codes=c(children(c("7994","7837")),
                                                get_icd_from_ccs(c(NA))) %>% as.character(),
                                   icd10_codes=c(children(c("R64","R627")),
                                                 get_icd_from_ccs(c(NA),10)) %>% as.character(),
                                   group="Endocrine & Nutritional",
                                   include=TRUE,
                                   hosp=FALSE),
    
    failure_to_thrive_child = list(label="Failure to thrive (child)",
                                   icd9_codes=c(children(c("78341")),
                                                get_icd_from_ccs(c(NA))) %>% as.character(),
                                   icd10_codes=c(children(c("R6251")),
                                                 get_icd_from_ccs(c(NA),10)) %>% as.character(),
                                   group="Endocrine & Nutritional",
                                   include=TRUE,
                                   hosp=FALSE),
    
    fecal_impaction = list(label="Fecal impaction",
                           icd9_codes=c(children(c("56032")),
                                        get_icd_from_ccs(c(NA))) %>% as.character(),
                           icd10_codes=c(children(c("K5641")),
                                         get_icd_from_ccs(c(NA),10)) %>% as.character(),
                           group="Gastrointestinal",
                           include=TRUE,
                           hosp=FALSE),
    
    feeding_difficulties = list(label="Feeding difficulties and mismanagement",
                                icd9_codes=c(children(c("7833")),
                                             get_icd_from_ccs(c(NA))) %>% as.character(),
                                icd10_codes=c(children(c("R633")),
                                              get_icd_from_ccs(c(NA),10)) %>% as.character(),
                                group="Endocrine & Nutritional",
                                include=TRUE,
                                hosp=FALSE),
    
    fluid_electrolyte = list(label="Fluid and electrolyte disorders",
                             icd9_codes=c(#children(c("99999")),
                               get_icd_from_ccs(c(55))) %>% as.character(),
                             icd10_codes=c(#children(c("99999")),
                               get_icd_from_ccs(c(55),10)) %>% as.character(),
                             group="Renal",
                             include=TRUE,
                             hosp=TRUE),
    
    gerd = list(label="GERD",
                icd9_codes=c(children(c("53081")),
                             get_icd_from_ccs(c(NA))) %>% as.character(),
                icd10_codes=c(children(c("K21")),
                              get_icd_from_ccs(c(NA),10)) %>% as.character(),
                group="Gastrointestinal",
                include=TRUE,
                hosp=FALSE),
    
    
    hemoptysis = list(label="Hemoptysis",
                      icd9_codes=c(children(c("7863")),
                                   get_icd_from_ccs(c(NA))) %>% as.character(),
                      icd10_codes=c(children(c("R042","R048","R049")),
                                    get_icd_from_ccs(c(NA),10)) %>% as.character(),
                      group="Respiratory",
                      include=TRUE,
                      hosp=TRUE),
    
    hepatitis_chronic = list(label="Chronic Hepatitis",
                             icd9_codes=c(children(c("57141","57149","57140")),
                                          get_icd_from_ccs(c(NA))) %>% as.character(),
                             icd10_codes=c(children(c("K73")),
                                           get_icd_from_ccs(c(NA),10)) %>% as.character(),
                             group="Hepatobiliary",
                             include=TRUE,
                             hosp=FALSE),
    
    hypertrophic_osteoarthropathy = list(icd9_codes=c(children(c("7312")),
                                                      get_icd_from_ccs(c(NA))) %>% as.character(),
                                         icd10_codes=c(children(c("M8940")),
                                                       get_icd_from_ccs(c(NA),10)) %>% as.character(),
                                         group="Bone"),
    
    
    
    infert_male = list(label="Male infertility",
                       icd9_codes=as.character(children("606")),
                       icd10_codes=as.character(children("N46")),
                       group="Genitourinary",
                       include=TRUE,
                       hosp=FALSE),
    
    
    intestinal_atresia = list(label="Intestinal atresia",
                              icd9_codes=c(children(c("7511", "7512")),
                                           get_icd_from_ccs(c(NA))) %>% as.character(),
                              icd10_codes=c(children(c("Q419","Q429")),
                                            get_icd_from_ccs(c(NA),10)) %>% as.character(),
                              group="Gastrointestinal",
                              include=TRUE,
                              hosp=FALSE),
    
    intestinal_malabsorption = list(label="Intestinal Malabsorption",
                                    icd9_codes=c(children(c("579")),
                                                 get_icd_from_ccs(c(NA))) %>% as.character(),
                                    icd10_codes=c(children(c("K90")),
                                                  get_icd_from_ccs(c(NA),10)) %>% as.character(),
                                    group="Pancreatic",
                                    include=TRUE,
                                    hosp=FALSE),
    
    intestinal_obstruction = list(label="Intestinal obstruction",
                                  icd9_codes=c(children(c("560")),
                                               get_icd_from_ccs(c(NA))) %>% as.character(),
                                  icd10_codes=c(children(c("K56")),
                                                get_icd_from_ccs(c(NA),10)) %>% as.character(),
                                  group="Gastrointestinal",
                                  include=TRUE,
                                  hosp=TRUE),
    
    
    
    jaundice = list(label="Jaundice (not of newborn)",
                    icd9_codes=c(children(c("7824")),
                                 get_icd_from_ccs(c(NA))) %>% as.character(),
                    icd10_codes=c(children(c("R17")),
                                  get_icd_from_ccs(c(NA),10)) %>% as.character(),
                    group="Hepatobiliary",
                    include=TRUE,
                    hosp=FALSE),
    
    
    liver_enzyme = list(label="Abnormal liver serum enzyme levels",
                        icd9_codes=c(children(c("7905")),
                                     get_icd_from_ccs(c(NA))) %>% as.character(),
                        icd10_codes=c(children(c("R748")),
                                      get_icd_from_ccs(c(NA),10)) %>% as.character(),
                        group="Hepatobiliary",
                        include=TRUE,
                        hosp=FALSE),
    
    mycobact = list(label="Nontuberculous Mycobacterial Infection",
                    icd9_codes=as.character(children(c("031"))),
                    icd10_codes=as.character(children(c("A31"))),
                    group="Respiratory Infection",
                    include=TRUE,
                    hosp=TRUE),
    
    meconium_ileus = list(label="Meconium obstruction in fetus or newborn",
                          icd9_codes = as.character(children(c("7771"))),
                          icd10_codes = as.character(children(c("P760"))),
                          group="Gastrointestinal",
                          include=TRUE,
                          hosp=FALSE),
    
    meconium_peritonitis = list(label="Meconium peritonitis",
                                icd9_codes=c(children(c("7776")),
                                             get_icd_from_ccs(c(NA))) %>% as.character(),
                                icd10_codes=c(children(c("P780")),
                                              get_icd_from_ccs(c(NA),10)) %>% as.character(),
                                group="Gastrointestinal",
                                include=TRUE,
                                hosp=FALSE),
    
    nasal_polyps = list(label="Nasal Polyposis",
                        icd9_codes=as.character(children(c("471"))),
                        icd10_codes=as.character(children(c("J33"))),
                        group="Respiratory",
                        include=TRUE,
                        hosp=FALSE),
    
    nausea_vomitting = list(label="Nausea or Vomiting",
                            icd9_codes=c(children(c("5362","56987","78701","78703","78704","78720")),
                                         get_icd_from_ccs(c(NA))) %>% as.character(),
                            icd10_codes=c(children(c("R110","R111","R112")),
                                          get_icd_from_ccs(c(NA),10)) %>% as.character(),
                            group="Gastrointestinal Symptoms",
                            include=TRUE,
                            hosp=TRUE),
    
    nephrolithiasis = list(label="Nephrolithiasis",
                           icd9_codes=c(children(c("5920")),
                                        get_icd_from_ccs(c(NA))) %>% as.character(),
                           icd10_codes=c(children(c("N200")),
                                         get_icd_from_ccs(c(NA))) %>% as.character(),
                           group="Renal",
                           include=TRUE,
                           hosp=TRUE),
    
    neonatal_jaundice = list(label="Neonatal jaundice",
                             icd9_codes=c(children(c("774")),
                                          get_icd_from_ccs(c(NA))) %>% as.character(),
                             icd10_codes=c(children(c("P57","P58","P59")),
                                           get_icd_from_ccs(c(NA),10)) %>% as.character(),
                             group="Hepatobiliary",
                             include=TRUE,
                             hosp=FALSE),
    
    osteopenia = list(label="Osteopenia",
                      icd9_codes=c(children(c("73390")),
                                   get_icd_from_ccs(c(NA))) %>% as.character(),
                      icd10_codes=c(children(c("M8580")),
                                    get_icd_from_ccs(c(NA),10)) %>% as.character(),
                      group="Bone",
                      include=TRUE,
                      hosp=FALSE),
    
    osteoporosis = list(label="Osteoporosis",
                        icd9_codes=as.character(get_icd_from_ccs(c(206))),
                        icd10_codes=as.character(get_icd_from_ccs(c(206),icd_version = 10)),
                        group="Bone",
                        include=TRUE,
                        hosp=FALSE),
    
    
    other_pancreatic = list(label="Other Pancreatic Disorders",
                            icd9_codes=c(children(c("5778","5779")),
                                         get_icd_from_ccs(c(NA))) %>% as.character(),
                            icd10_codes=c((as.character(c("K868","K8681","K9689","K869"))),
                                          get_icd_from_ccs(c(NA),10)) %>% as.character(),
                            group="Pancreatic",
                            include=TRUE,
                            hosp=TRUE),
    
    pancreatic_cysts = list(label="Cyst/pseudocyst of pancreas",
                            icd9_codes=c(children(c("5772")),
                                         get_icd_from_ccs(c(NA))) %>% as.character(),
                            icd10_codes=c(children(c("K862","K863")),
                                          get_icd_from_ccs(c(NA),10)) %>% as.character(),
                            group="Pancreatic",
                            include=TRUE,
                            hosp=FALSE),
    
    pancreatitis_acute = list(label="Pancreatitis (Acute)",
                              icd9_codes=c(children(c("5770")),
                                           get_icd_from_ccs(c(NA))) %>% as.character(),
                              icd10_codes=c(children(c("K85")),
                                            get_icd_from_ccs(c(NA),10)) %>% as.character(),
                              group="Pancreatic",
                              include=TRUE,
                              hosp=TRUE),
    
    pancreatitis_chronic = list(label="Pancreatitis (Chronic)",
                                icd9_codes=c(children(c("5771")),
                                             get_icd_from_ccs(c(NA))) %>% as.character(),
                                icd10_codes=c(children(c("K861")),
                                              get_icd_from_ccs(c(NA),10)) %>% as.character(),
                                group="Pancreatic",
                                include=TRUE,
                                hosp=TRUE),
    
    pancreatic_steatorrhea = list(label="Pancreatic Steatorrhea",
                                  icd9_codes=c(children(c("5794")),
                                               get_icd_from_ccs(c(NA))) %>% as.character(),
                                  icd10_codes=c(children(c("K903")),
                                                get_icd_from_ccs(c(NA),10)) %>% as.character(),
                                  group="Pancreatic",
                                  include=TRUE,
                                  hosp=TRUE),
    
    pneumonia = list(label="Pneumonia",
                         icd9_codes=as.character(get_icd_from_ccs(c(122))),
                         icd10_codes=as.character(get_icd_from_ccs(c(122),icd_version = 10)),
                         group="Respiratory Infection",
                         include=TRUE,
                         hosp=TRUE),
    
    pneumonia_recurrent = list(label="Personal history of recurrent pneumonia",
                               icd9_codes=as.character(children(c("V1261"))),
                               icd10_codes=as.character(children(c("Z8701"))),
                               group="Respiratory Infection",
                               include=TRUE,
                               hosp=FALSE),
    
    pneumonia_congenital = list(label="Congenital pneumonia",
                                icd9_codes=as.character(children(c("7700"))),
                                icd10_codes=as.character(children(c("P23"))),
                                group="Respiratory Infection",
                                include=TRUE,
                                hosp=FALSE),
    
    pseudomonas = list(label="Pseudomonas Infections",
                       icd9_codes=c(children(c("0417","4821")),
                                    get_icd_from_ccs(c(NA))) %>% as.character(),
                       icd10_codes=c(children(c("B965","J151")),
                                     get_icd_from_ccs(c(NA),10)) %>% as.character(),
                       group="Respiratory Infection",
                       include=TRUE,
                       hosp=TRUE),
    
    resp_fail = list(label="Respiratory Failure",
                     icd9_codes=c(children(c("51851","51852","51853","51881","51882","51883","51884","51889")),
                                  get_icd_from_ccs(c(NA))) %>% as.character(),
                     icd10_codes=c(children(c("J96","J95821","J951","J952","J953","J95822","J80","J9610","J984")),
                                   get_icd_from_ccs(c(NA),10)) %>% as.character(),
                     group="Respiratory",
                     include=TRUE,
                     hosp=TRUE),
    
    resp_fail_newborn = list(label="Respiratory Failure of Newborn",
                             icd9_codes=c(children(c("77081","77082","77083","77084","77087","77088","77089")),
                                          get_icd_from_ccs(c(NA))) %>% as.character(),
                             icd10_codes=c(children(c("P283","P284","P282","P285","P2881","P84","P2889")),
                                           get_icd_from_ccs(c(NA),10)) %>% as.character(),
                             group="Respiratory",
                             include=TRUE,
                             hosp=TRUE),
    
    scoliosis = list(label="Scoliosis",
                     icd9_codes=c(children(c("73730")),
                                  get_icd_from_ccs(c(NA))) %>% as.character(),
                     icd10_codes=c(children(c("M4120")),
                                   get_icd_from_ccs(c(NA),10)) %>% as.character(),
                     group="Bone",
                     include=TRUE,
                     hosp=FALSE),
    
    short_stature = list(label="Short stature",
                         icd9_codes=c(children(c("78343")),
                                      get_icd_from_ccs(c(NA))) %>% as.character(),
                         icd10_codes=c(children(c("R6252")),
                                       get_icd_from_ccs(c(NA),10)) %>% as.character(),
                         group="Endocrine & Nutritional",
                         include=TRUE,
                         hosp=FALSE),
    
    lack_of_development = list(label="Lack of Expected Normal Development",
                               icd9_codes=c(children(c("78340")),
                                            get_icd_from_ccs(c(NA))) %>% as.character(),
                               icd10_codes=c(children(c("R6250")),
                                             get_icd_from_ccs(c(NA),10)) %>% as.character(),
                               group="Endocrine & Nutritional",
                               include=TRUE,
                               hosp=FALSE),
    
    
    sinusitis_acute = list(label="Acute Sinusitis",
                           icd9_codes=children(as.character(c("4610","4611","4612","4613","4618"))),
                           icd10_codes=children(c("J010","J011","J012","J013","J014","J018")),
                           group="Respiratory Infection",
                           include=TRUE,
                           hosp=TRUE),
    
    sinusitis_chronic = list(label="Chronic Sinusitis",
                           icd9_codes=children(as.character(c("4730","4731","4732","4733","4738","4739"))),
                           icd10_codes=children(c("J320","J321","J322","J323","J324","J328","J329")),
                           group="Respiratory Infection",
                           include=TRUE,
                           hosp=TRUE),
    
    venous_thromboembolism =list(label="Venous thromboembolism",
                                 icd9_codes=c(children(c("453","451")),
                                              get_icd_from_ccs(c(NA))) %>% as.character(),
                                 icd10_codes=c(children(as.character(c("453","451"))) %>% icd9_to_icd10(),
                                               get_icd_from_ccs(c(NA),10)) %>% as.character(),
                                 group="Hematologic",
                                 include=TRUE,
                                 hosp=TRUE)
    
    
  )
  
  return(out_list)
}

