

rm(list=ls()) 
#library(bit64)
library(bit64)
library(tidyverse)
library(survival)
#library(multidplyr)
library(multidplyr)
library(parallel)
source("analysis_functions.R")


######################################
##### Simulation for FDR Analysis ####
######################################

# load in data for the full carrier cohort. Note: this dataset contains all of the carriers plus any
# non-carriers that can be matched (i.e., more than the 5 that were in the original match). This dataset
# can be generated by returning to the scripts build_marched_cohorts.R and removeing the filtering step
# and to the main_analysis.R script

load("<path to full_carrier_cohort_ins.RData>")


##### Build Timemap ####

# conditions to simulate
sim_conds <- tibble(name=names(select(carrier_cohort_inds,abdominal_pain:venous_thromboembolism)))

# study results to compare to
compare_res <- select(carrier_or,name,est_or=or,est_p_val=or_p_val)

## add in both groups
sim_dx_inds <- select(full_carrier_cohort_inds,strata,enrolid,abdominal_pain:venous_thromboembolism)

full_carrier_cohort_inds %>% 
  filter(case==0) %>% 
  count(strata,sex,first_age,enrmon) %>% 
  group_by(strata) %>% 
  nest()

# create strata to use in the simulation
sim_strata <- full_carrier_cohort_inds %>% 
  filter(case==0) %>% 
  select(strata,enrolid,abdominal_pain:venous_thromboembolism) %>% 
  group_by(strata) %>% 
  nest() %>% 
  inner_join(full_carrier_cohort_inds %>% 
               filter(case==1) %>% 
               count(strata) %>% 
               rename(num_cases=n),
             by="strata") %>% 
  mutate(data=map(data,~select(.,enrolid)))

# simulation of randomly drawing conditions and estimating odds ratio
sim_fdr <- function(){
  sim_draw <- sim_strata %>% 
    mutate(case_draw=map2(data,num_cases,~sample_n(tbl = .x,
                                                   size = .y,
                                                   replace = TRUE)),
           control_draw=map2(data,num_cases,~sample_n(tbl = .x,
                                                      size = 5*.y,
                                                      replace = TRUE)))
  
  sim_inds <- bind_rows(select(sim_draw,case_draw) %>% 
                          unnest() %>% 
                          mutate(case=1L),
                        select(sim_draw,control_draw) %>% 
                          unnest() %>% 
                          mutate(case=0L)) %>% 
    inner_join(sim_dx_inds,by="enrolid")
  
  sim_or <- sim_conds %>%
    mutate(or=map(name,~sim_get_paired_or(sim_inds,.))) %>% 
    unnest()  
  
  res <- sim_or %>% 
    inner_join(compare_res,by="name") %>% 
    filter(or>1 & or_p_val<0.1) %>% 
    summarise(n_sig=n(),
              n_same_est=sum(or>=est_or),
              n_same_p=sum(or_p_val<=est_p_val))
  
  return(res)
  
}

#########################
#### Run simulation #####
#########################

#### Setup cluster
cluster <- create_cluster(50) 
cluster_library(cluster, "tidyverse")
cluster_library(cluster, "survival")
parallel::clusterExport(cluster, list("sim_fdr","sim_strata","sim_dx_inds","sim_conds",
                                      "sim_get_paired_or","compare_res"))

# run simulation
sim_res <- tibble(trial=1:1000) %>% 
  partition(trial, cluster = cluster) %>% 
  mutate(data=map(trial,~sim_fdr())) %>% 
  collect()

# save results
save(sim_res,file = "<path to file>")


#######################################
#### Missclassification Simulation ####
#######################################

# Uncomment this to find the p-values for the 2 missclassification rates
# # Output file
# out_file <- "missclass_sim1_1mil.RData"
# # number of trials
# n_trials <- 1000000
# # vector of missclassification values
# miss_vect <- c(58,117)
# # setup grid 
# miss_grid <- FALSE


# For finding the the cutoffs for the requried missclassification rates
out_file <- "missclass_sim2.RData"
n_trials <- 1000
miss_vect <- seq(from=0, to=10000,by=25)
miss_grid <- TRUE


##### Load SIM Data ####

# Load in required simulation data. The simulation data contains the all of the cf patients and
# non-carriers that can be matched to the carriers. Return to the build_matched_cohorts.R script
# and remove the restrictions on the number matched to find all enrollees that could be potential 
# matches. Then re-build the database using all these enrolids. Finally, use the main anlaysis.R 
# script to create indicators for each of the conditions.
load("<all_sim_data.RData>")

#### Simulation Function ####

sim_missclass <- function(n_miss){
  
  # draw cf cases
  cf_draw <- cf_case_matches %>% 
    sample_n(n_miss) %>% 
    arrange(strata) %>% 
    group_by(strata) %>% 
    mutate(strata_num=row_number()) %>% 
    filter(strata_num<=strata_size) %>% 
    ungroup() %>% 
    select(-strata_size,-strata_num) %>% 
    mutate(case=1L)
  
  # replace the controls labelled as missclassified carriers with cf cases
  sim_draw <- sim_strata %>% 
    left_join(cf_draw %>% 
                count(strata) %>% 
                rename(n_miss_draw=n),   # number of missing cases per strata
              by="strata") %>%
    mutate(n_miss_draw=ifelse(is.na(n_miss_draw),0L,n_miss_draw),
           n_carrier_draw=num_cases-n_miss_draw) %>% 
    mutate(case_draw=map2(non_carriers,n_carrier_draw,~sample_n(tbl = .x,
                                                                size = .y,
                                                                replace = TRUE)),
           control_draw=map2(non_carriers,num_cases,~sample_n(tbl = .x,
                                                              size = 5*.y,
                                                              replace = TRUE)))
  # assemble the condition indicators
  sim_inds <- bind_rows(select(sim_draw,case_draw) %>% 
                          unnest() %>% 
                          mutate(case=1L),
                        select(sim_draw,control_draw) %>% 
                          unnest() %>% 
                          mutate(case=0L),
                        select(cf_draw,enrolid,case)) %>% 
    inner_join(sim_dx_inds,by="enrolid")
  
  sim_inds
  
  # uncomment the following to run using the regression model
  # sim_or <- sim_conds %>%
  #   mutate(or=map(name,~sim_get_paired_or(sim_inds,.))) %>% 
  #   unnest()  
  
  # compute simple odds ratios manually
  sim_or <- sim_inds %>% 
    summarise_at(vars(-enrolid,-case,-strata),funs((sum(case==1 & .==1)/
                                                      (case_count-sum(case==1 & .==1)))/
                                                     (sum(case==0 & .==1)/
                                                        (control_count-sum(case==0 & .==1)))))
  # uncomment to summarise the simulation output
  # res <- sim_or %>% 
  #   inner_join(compare_res,by="name") %>% 
  #   filter(or>1 & or_p_val<0.1) %>% 
  #   summarise(n_sig=n(),
  #             n_same_est=sum(or>=est_or),
  #             n_same_p=sum(or_p_val<=est_p_val))
  
  return(sim_or)
  
}

# function to run multiple simulations
multi_sim <- function(n_miss,trials){
  tibble(trial=1:trials) %>% 
    mutate(data=map(trial,~sim_missclass(n_miss)))
}

#### Build Cluster #####
#cluster <- create_cluster(4) 
cluster <- create_cluster(28) 
cluster_library(cluster, "tidyverse")
cluster_library(cluster, "survival")
parallel::clusterExport(cluster, list("multi_sim","sim_missclass","sim_strata","sim_dx_inds","sim_conds",
                                      "sim_get_paired_or","compare_res","cf_case_matches",
                                      "case_count","control_count","n_trials","miss_vect"))


#### Get Results ####

# setup a grid of results
if (miss_grid) {
  
  set.seed(1234)
  sim_res <- tibble(num_miss=miss_vect) %>% 
    partition(num_miss, cluster = cluster) %>% 
    mutate(sim_data=map(num_miss,~multi_sim(.,n_trials))) %>% 
    collect()
  
} else {
  
  set.seed(1234)
  temp_res1 <- tibble(trial=1:n_trials) %>% 
    partition(trial, cluster = cluster) %>% 
    mutate(sim_data=map(trial,~sim_missclass(miss_vect[1]))) %>% 
    collect()
  
  set.seed(1234)
  temp_res2 <- tibble(trial=1:n_trials) %>% 
    partition(trial, cluster = cluster) %>% 
    mutate(sim_data=map(trial,~sim_missclass(miss_vect[2]))) %>% 
    collect()
  
  sim_res <- list(res1 = list(miss_num = miss_vect[1],
                              sim_res = temp_res1),
                  res2 = list(miss_num = miss_vect[2],
                              sim_res = temp_res2))
  
}

# save simulation results
save(sim_res,file = "<path to simulation output>")





